# Changes here will be overwritten by Copier.
_commit: 1.10.2
_src_path: gh:pawamoy/copier-uv
author_email: lespana@mcw.edu
author_fullname: Lezlie Espana
author_username: l-espana
copyright_date: '2025'
copyright_holder: mcw-meier-lab
copyright_holder_email: lespana@mcw.edu
copyright_license: MIT
insiders: false
project_description: Python tools for FreeSurfer visualization and QA
project_name: pyFS
python_package_command_line_name: pyfs
python_package_distribution_name: pyfs
python_package_import_name: pyfs
repository_name: pyFS
repository_namespace: mcw-meier-lab
repository_provider: github.com

