name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install MkDocs and dependencies
        run: pip install markdown-callouts>=0.4 markdown-exec>=1.8 mkdocs>=1.6 mkdocs-api-autonav>=0.4.0 mkdocs-autoapi>=0.4.1 mkdocs-coverage>=1.0 mkdocs-git-revision-date-localized-plugin>=1.2 mkdocs-llmstxt>=0.2 mkdocs-material>=9.5 mkdocs-minify-plugin>=0.8 mkdocs-section-index>=0.3 mkdocstrings[python]>=0.29

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force